### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#86] opened 2016-06-10 22:35 UTC
Hello to all,

I am experiencing the following crash while trying to work with data channels:

http://pastebin.com/raw/g08QwzSP

Looks like something in there is NULL.

The hash we currently use: `23dc752d65e753de51a3c4e6ef0145a6b02a789c`

Link to the indicated SIGSEGV:
https://github.com/sctplab/usrsctp/blob/23dc752d65e753de51a3c4e6ef0145a6b02a789c/usrsctplib/user_socket.c#L1166

**Comment by tuexen** [comment] 2016-06-11 08:00
Can you provide the output of
`print *so`
from a debugger?

**Comment by shiretu** [comment] 2016-06-14 12:39
Hi @tuexen,

I don't have access to that unfortunately. But it appears that we have another one which I am told is quite consistent:

http://pastebin.com/raw/P4tD6Q5d

The guys are telling me this is not happening on an older version of the SCTP library. I will get more details about what is the good hash. maybe we can do some divide-et-impera between the hashes and identify the commit which triggers this.

**Comment by shiretu** [comment] 2016-06-14 23:29
Hi @tuexen,

More info: we have a way to reproduce this easy enough, we just need to have a lot of patience to do that. We have found that at some point, the library doesn't exit `sctp_sorecvmsg` and it spins in it forever, causing the CPU to spike to 100%. When that happens, the iOS watchdog is eventually killing the app kinda brutal.

<img width="658" alt="screenshot 2016-06-15 02 25 53" src="https://cloud.githubusercontent.com/assets/7860758/16063266/e867dc4a-32a0-11e6-8945-f810e074a0d5.png">

**Comment by tuexen** [comment] 2016-06-14 23:44
OK. Any possibility to describe what happens on the network, which triggers this? Or any chance to be more specific about where in sctp_sorecvmsg() the library is spinning?

**Comment by zombieobject** [comment] 2016-06-14 23:54
@tuexen Our repro scenario is often a distant network link with a relatively high latency. 

Thread snapshot: 
![sctp-snapshot](https://cloud.githubusercontent.com/assets/7294166/16063789/a4437cf4-3250-11e6-8427-ca797e992ed4.png)

**Comment by zombieobject** [comment] 2016-06-14 23:58
I can provide disassembly from that if needed.

**Comment by shiretu** [comment] 2016-06-15 00:17
@tuexen: It always jumps here:

https://github.com/sctplab/usrsctp/blob/23dc752d65e753de51a3c4e6ef0145a6b02a789c/usrsctplib/netinet/sctputil.c#L5721

We use `23dc752d65e753de` revision

Here is how we found that:
<img width="690" alt="screenshot 2016-06-15 03 14 45" src="https://cloud.githubusercontent.com/assets/7860758/16064195/9d9780c4-32a7-11e6-9b38-64f691b5554f.png">

**Comment by shiretu** [comment] 2016-06-15 00:32
@tuexen I have traced the assembly code, and matched it manually with the sources, and the jump point is from here:

https://github.com/sctplab/usrsctp/blob/23dc752d65e753de51a3c4e6ef0145a6b02a789c/usrsctplib/netinet/sctputil.c#L5985

**Comment by tuexen** [comment] 2016-06-15 19:46
OK. That helps. Need to think about this. This code has changed recently when adding support for the I-DATA chunk. So it is possible that a bug was introduced here. Any possibility that you can provide a .pcapng file which illustrates how to run into such a problem?

**Comment by shiretu** [comment] 2016-06-15 21:52
I will try to do that.

**Comment by tuexen** [comment] 2016-06-17 20:34
Please try the fix in the issue86 branch and report if it fixes the issue.

**Comment by shiretu** [comment] 2016-06-17 20:59
Will do ASAP!
Tx for the quick support

**Comment by shiretu** [comment] 2016-06-22 19:32
@tuexen Is the https://github.com/sctplab/usrsctp/commit/cc6ff45cf7bcc0173572e76e64ec6232733107fb final? Can we safely use it? For now, it does fix the issue, but I do not see it merged

**Comment by tuexen** [comment] 2016-06-22 19:40
It is not merged since you wanted to test it for a couple of days. Since I wasn't able to reproduce the problem, I thought that is a good idea. If you say, it fixes the issue, I'll get do some cleanup in other places, get the stuff into FreeBSD and merge it. This might take a day or two. But you can use it. I think that is the fix. The cleanups are in other places to get a more consistent handling of the sequence of changing counters...

**Comment by shiretu** [comment] 2016-06-22 21:06
Hi Michael,

I think I forgot to let you know that it works in our tests.

We will wait for the merge than.

Best regards,
Andrei

**Comment by tuexen** [comment] 2016-06-23 19:38
Hi Andrei,

it is merged now, so I'm closing the issue.

Best regards
Michael

**Closed by tuexen** 2016-06-23 19:38 UTC
