### ISSUE TITLE
Memory leak under Windows

### ISSUE THREAD

**Issue by jswirl** [sctplab/usrsctp#49] opened 2016-02-04 10:12 UTC
![usrsctptest4](https://cloud.githubusercontent.com/assets/12203848/12811587/6d98840a-cb68-11e5-9290-5b4221bc2a92.png)
This is after applying this PR: https://github.com/sctplab/usrsctp/pull/48
I'm not really familiar with Windows, so I could be doing something wrong, but it appears there may be leaks some place else.

The Windows UMDH utility seems to point to some suspicious parts in sctp_init_ifns_for_vrf():
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_bsd_addr.c#L356-L362 and
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_bsd_addr.c#L404-L409.

Here's the UMDH log from the test program I used:
[stackdiff.txt](https://github.com/sctplab/usrsctp/files/117188/stackdiff.txt)

**Comment by tuexen** [comment] 2016-02-11 19:35
OK. Can you retest with the current code? If the problem persists, could you share your test program?

**Comment by Globik** [comment] 2016-02-11 20:18
Аnd I am on windows with msys2. I cant find netinet6 with headers files. What is the name of such library for netinet6?

**Comment by tuexen** [comment] 2016-02-11 21:15
I guess the files are in
https://github.com/sctplab/usrsctp/tree/master/usrsctplib/netinet6
You should be able to build the userland stack with nmake or cmake.

**Comment by tuexen** [comment] 2016-02-12 10:55
OK, found the test program. Wasn't reading the screenshot... We will test it.

**Comment by tuexen** [comment] 2016-02-12 14:11
I added a simple test program [test_libmgmt.c](https://github.com/sctplab/usrsctp/blob/master/programs/test_libmgmt.c) and it doesn't show any leaks on Linux. We will test it on Windows next week.

Please note that you must use
```
while (usrsctp_finish() != 0) {
#ifdef _WIN32
	Sleep(1000);
#else
	sleep(1);
#endif
}
```
instead of
```
usrsctp_finish();
```
in your test program. If usrsctp_finish() does return a non-zero value, the stack is not cleaned up and you might leak memory when just calling usrsctp_init() again.

**Comment by jswirl** [comment] 2016-02-13 17:23
Okay. I don't have access to my Windows machine now, but I'll test it on Monday and let you know.
Thanks for your help.

**Comment by tuexen** [comment] 2016-02-14 09:13
I now see where the leak occurs on Windows. It doesn't occur on other platforms. Need to think about a correct way of fixing it. Will let you know when I think the issue is fixed.

**Comment by jswirl** [comment] 2016-02-15 09:34
I can confirm that there are still leaks using the most recent code, this time I waited for `usrsctp_finish()` to return properly before calling `usrsctp_init()`
![usrsctptest5](https://cloud.githubusercontent.com/assets/12203848/13044651/3a87cba2-d40a-11e5-8491-fc1214343f2e.png)

**Comment by jswirl** [comment] 2016-02-15 09:36
@tuexen: just out of curiosity, where is the leak that you said you saw?
thanks.

**Comment by tuexen** [comment] 2016-02-15 09:56
The allocations in
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_bsd_addr.c#L357
and
https://github.com/sctplab/usrsctp/blob/master/usrsctplib/netinet/sctp_bsd_addr.c#L405
are never freed.
On the other platforms we use a global list which is freed at the end. In the FreeBSD Kernel we use pointers to a global list of addresses which never goes away.
I need to check if we actually use these pointers in the userland stack, or if a NULL pointer can be provided. If we use the global list, it should be updated when addresses are added to deleted to the stack. Not sure if this happens. I need to check that.

**Comment by tuexen** [comment] 2016-02-20 11:53
OK. This should be fixed now. Can you retest?

**Comment by jswirl** [comment] 2016-02-22 08:37
![usrsctptest6](https://cloud.githubusercontent.com/assets/12203848/13213211/30846f48-d982-11e5-93d3-faa2d64a5ac8.png)

@tuexen: Yes, it appears to be no longer leaking. Thanks so much for your help!

**Closed** 2016-02-22 13:21 UTC
