### ISSUE TITLE
Build failure with -Wsign-compare -Werror (default on Ubuntu for ARM builds)

### ISSUE THREAD

**Issue by dreibh** [sctplab/usrsctp#336] opened 2019-08-05 17:42 UTC
Building fails on Ubuntu for ARM, due to signed/unsigned comparison warning (handled as error by default):

/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c: In function ‘sctp_lower_sosend’:
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c:13898:14: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (sndlen > asoc->smallest_mtu) {
              ^
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c:13933:15: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if (sndlen > SCTP_SB_LIMIT_SND(so))
               ^
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c:14129:14: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
      (sndlen > SCTP_SB_LIMIT_SND(stcb->sctp_socket))) {
              ^
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c:14158:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  if (((max_len <= local_add_more) &&
                ^~
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctp_output.c:14312:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((max_len > SCTP_BASE_SYSCTL(sctp_add_more_threshold)) ||
                 ^
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctputil.c: In function ‘sctp_sorecvmsg’:
/<<PKGBUILDDIR>>/usrsctplib/netinet/sctputil.c:6447:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
        (copied_so_far >= (uint32_t)max(so->so_rcv.sb_lowat, 1)))) {

**Comment by tuexen** [comment] 2019-08-05 17:46
I think this is a duplicate of #335.

**Closed** 2019-08-05 17:47 UTC
