### ISSUE TITLE
usrsctp in Windows 8 stop sending data when calling usrsctp_sendv() mulitple times in for loop.

### ISSUE THREAD

**Issue by androidpdn** [sctplab/usrsctp#410] opened 2019-12-09 22:15 UTC
Hi,
I built the usrsctp using Visual Studio 2019 on 64bits Windows 8, and modified the client.c file to send a fixed 5 bytes buffer multiple times in a for loop.
The client is connected to a Linux server running usrsctp echo server.

Depending on the number of loops, the usrsctp behaves differently.
E.g. if I make it loop for 50 times, i.e. calling usrsctp_sendv() 50 times to send the fixed 5 bytes buffer, all 50 piece of data are sent out and received back.
But, if I make it loop for 100 times, only 1 piece of data is sent on the wire (this is confirmed by the wireshark capture), and the usrsctp stack stop sending the rest of the data, even though each call to the usrsctp_sendv() return 5, i.e. the length of buffer being sent.

I turn on the debug traces by calling usrsctp_sysctl_set_sctp_debug_on(0x0040), and get the following information:
[0.000] src_loop:0 src_priv:1 src_glob:0
[0.001] dest_loop:0 dest_priv:1 dest_glob:0
[0.001] YES
[0.001] src_loop:0 src_priv:1 src_glob:0
[0.001] dest_loop:0 dest_priv:1 dest_glob:0
[0.001] YES
[0.002] Calling ipv4 output routine from low level src addr:ac10461c
[0.002] Destination is ac104629
[0.002] RTP route is 000000A7B889D820 through
[0.002] IP output returns 0
[0.004] Calling ipv4 output routine from low level src addr:ac10461c
[0.005] Destination is ac104629
[0.005] RTP route is 000000A7B889D820 through
[0.005] IP output returns 0
[0.006] m-c-o put out 0
[0.006] m-c-o put out 0
[0.007] Calling ipv4 output routine from low level src addr:ac10461c
[0.008] Destination is ac104629
[0.008] RTP route is 000000A7B889D820 through
[0.008] IP output returns 0
[0.009] m-c-o put out 1
[0.009] Calling ipv4 output routine from low level src addr:ac10461c
[0.010] Destination is ac104629
[0.010] RTP route is 000000A7B889D820 through
[0.010] IP output returns 10040
[0.011] Gak send error 10040
[0.011] m-c-o put out 0

I googled socket error 10040, which means message length too long. However what I'm sending is only 5 bytes data. It can't be too long. 

Could someone please help me on this issue?
Thanks!

**Comment by weinrank** [comment] 2020-01-22 14:17
Hi @androidpdn,

can you provide the sample program?

Best
Felix

**Comment by tuexen** [comment] 2020-02-04 22:43
> Hi @androidpdn,
> 
> can you provide the sample program?
> 
> Best
> Felix

I think he ist using `program/client.c` and has modified the loop around `sctp_sendv()`. Can you try that?

**Comment by androidpdn** [comment] 2020-02-24 17:50
Hi Felix and Michael,
Sorry for replying late. 
Michael is right, I modified the program/client.c by adding a loop to call sctp_sendv() multiple times.
I was able work around the issue by hard coding the MTU size to 1200 instead of let the stack to automatically learn the MTU. It seems to me there is a bug in the Windows related codes, as the same program works fine in Linux.
Thanks,
Hao

**Comment by tuexen** [comment] 2020-05-09 00:21
How are the Windows machine and the Linux Server connected? What is the MTU of the interface being used? Is there some tunneling involved?

**Comment by androidpdn** [comment] 2020-05-30 23:06
The Windows machine  is the host machine, the Linux Server is a virtual machine running on top of  VirtualBox which runs on the Windows machine.

**Comment by tuexen** [comment] 2020-05-31 11:55
What do you mean by `by hard coding the MTU size to 1200`? Please provide a diff.

**Comment by tuexen** [comment] 2020-06-14 13:12
@androidpdn Any chance we can debug this? This might require that you test some patches as we can't reproduce this locally.

**Comment by androidpdn** [comment] 2020-06-22 21:41
It was hardcoded to 1200  by calling usrsctp_set_fixed_mtu(psock, 1200);
Sorry, we moved to use the kernel sctp in Linux several months ago. All the setup for Windows had gone.

**Comment by tuexen** [comment] 2020-06-22 22:11
OK. Thanks for the feedback.

If you are sending 5 bytes user data, this ends up in a DATA chunk of length 16 + 5 +3 = 24 bytes. 50 user messages would therefore need 50 * 24 = 1200 bytes. In addition you would need 12 bytes common header, 20 bytes IPv4 header. This means 1232. This is in the area of 1200 bytes.
Not setting the MTU, would  result in using 61 user messages ending up in 20 + 12 * 61*24 = 1496 bytes. I guess that one of two things happened:

1. You had an MTU between the Windows machine and the server with an MTU less than 1496 bytes. So was is directly connected in a lab? Or was there some tunneling (VPN, for example) going on?

2. There is a bug in the SCTP stack which overshootes sometimes the MTU. That would also explain it.

Do you remember anything related to the first possibility?

**Comment by tuexen** [comment] 2020-06-23 16:39
Can't reproduce with an old version or the current version of usrsctp on Mac OS X using the client and server as described on the loopback interface. The configured MTU is honoured.
@weinrank: please test on Windows.

**Comment by tuexen** [comment] 2020-06-24 13:53
@weinrank was not able on Windows to trigger a situation where the configure MTU is exceeded. I was not able to do the same on Mac OS. So I guess, the MTU on the link between sender and receiver was smaller than 1500 bytes, which would explain the behaviour.

Since we can't debug this any further, I'm closing this issue.

**Closed by tuexen** 2020-06-24 13:53 UTC
